[package]
name = "magic-miner"
version = "0.1.0"
edition = "2021"
description = "21e8miner implemented in Rust"
repository = "https://github.com/blocksurf/21e8miner-wasm"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#wasm-bindgen = "0.2.87"
rayon = "1.7.0"
#wasm-bindgen-rayon = {version = "1.0.3", features = ["atomics", "bulk-memory"]}
bsv = "2.0.1"
colored = "2.0.0"
hex = "0.4.3"
serde_json = "1.0"
parking_lot = "0.12.1"
reqwest = { version = "0.11.18", features = ["blocking"] }
